### ISSUE TITLE
複製リストを作成

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#145]
下書きと登録ができるようにする。
slack通知は同様の役割にする。

検索窓は求人一覧と同様

作成ステータスを空の状態にする

**Comment by hiraokakoichi** [comment]
複製リストは作らない方針になった。
https://plusadgroup.slack.com/archives/C0413B0S4VD/p1696558208702709?thread_ts=1696495057.683619&cid=C0413B0S4VD
