### ISSUE TITLE
発注業務詳細

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#146]
発注業務詳細の縦幅を広げる

**Comment by yamamoto0603** [comment]
ランク外求人一覧スクロール追加
テキスト変更「求人一覧」→「ランク外求人一覧」

**Comment by hiraokakoichi** [comment]
@sugaigit 
> 発注業務詳細の縦幅を広げる

Slackでは「テキスト入力数を1000字にする」とありますが、textarea要素は文字数制限で入力欄のサイズをコントロールすることはできまえん。row属性とcol属性で横幅と縦幅を指定します。
とりあえず、自分のディスプレイで1000字入力しても隠れない程度（row=15）に設定してます、
