### ISSUE TITLE
【5】対応済み　資格・経験欄の「経験内容」のテキスト幅変更

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#164]
[https://docs.google.com/spreadsheets/d/1djbehIkxdXHqNEgKCuzpPa0zG6LZBd-gFHK-vW_o3S0/edit#gid=416000752](https://docs.google.com/spreadsheets/d/1djbehIkxdXHqNEgKCuzpPa0zG6LZBd-gFHK-vW_o3S0/edit#gid=416000752)
上記をもとにテキスト幅を調整

**Comment by hiraokakoichi** [comment]
背景色が赤のカラムについては対応完了しました。
