### ISSUE TITLE
対応済み　顧客一覧の企業ランクを「ランク＋（点数）」

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#175]

**Comment by hiraokakoichi** [comment]
求人ランク＝企業ランク＋商談ランク

求人ランク：D〜SSの６ランクで評価
企業ランク：5〜50点のポイントで評価
商談ランク：5〜100点のポイントで評価

企業ランクに現状、ランクは定義されてないですが、どうしますか？
