### ISSUE TITLE
項目の削除と位置変更

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#185]
求人掲載サイト・起算日を削除
人材紹介/紹介予定　採用後条件（特定の選択肢でのみ表示）を作成ステータスの上に配置

活動記録に編集機能の追加・改行ができるテキストエリアにする。

**Comment by hiraokakoichi** [comment]
> 求人掲載サイト・起算日を削除

csvインポート機能に影響がでる可能性あり
