### ISSUE TITLE
須貝【普通】求人・顧客一覧画面での表示項目の追加・変更

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#31]
営業部にもらった パワーポイントを参照

**Comment by hiraokakoichi** [comment]
https://docs.google.com/presentation/d/1AAXeDq2IiVNY6gykGxxEAgvIQaq90uWK/edit#slide=id.p2

**Comment by hiraokakoichi** [comment]
issueを閉じるときに以下のissue番号40のタイトルを以下の通り変更して頂けないでしょうか？
■issueを閉じる前
<保留>平岡【高】一覧ページの見え方の変更 #40
■issueを閉じる時
平岡【高】一覧ページの見え方の変更 #40
