### ISSUE TITLE
平岡　今週中【普通】求人・顧客一覧で企業名をクリックすると詳細のリンクに飛ばす

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#32]
@hiraokakoichi 
[営業部システム](https://docs.google.com/spreadsheets/d/1djbehIkxdXHqNEgKCuzpPa0zG6LZBd-gFHK-vW_o3S0/edit#gid=1333524448&range=B56)の59と60をお願いします。

**Comment by hiraokakoichi** [comment]
【須貝】一覧画面に「顧客」を追加する。
↓
【平岡】顧客詳細画面へのリンクを貼る。
