### ISSUE TITLE
平岡【高】求人ランクについて

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#35]
求人ランクがCかDだった場合は登録ではなく下書きに移行する
求人ランクとCより上だった場合は登録をする

顧客新規登録は企業ランクに関係なく登録が可能

[※テーブル定義参照](https://docs.google.com/spreadsheets/d/1djbehIkxdXHqNEgKCuzpPa0zG6LZBd-gFHK-vW_o3S0/edit#gid=119074845&range=C61)

**Comment by hiraokakoichi** [comment]
顧客は企業ランクをもつ
求人情報は商談ランクをもつ
求人情報新規登録時
企業ランク＋商談ランク＝求人ランク

■求人ランク資料
https://docs.google.com/spreadsheets/d/1VJM2uhGigCk0Lsg_He5ZJ-oWGr4o1SwB/edit#gid=30032893

**Comment by hiraokakoichi** [comment]
【仕様確認】
customersテーブルの企業ランク関連カラムはnull可となっているが、企業ランクポイントはnullの場合0で良いか？
