### ISSUE TITLE
＜遅れてる＞平岡【高】顧客登録の際にプラスボタンで入力内容の追加

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#38]
顧客登録の際にプラスボタンで追加マイナスボタンで削除
支店名,担当者所属部署,担当者名,顧客住所,電話番号,メールアドレス,FAXを表示させるようにする。

仕様は求人登録の支払い単価①・支払い単位①などと同じにして、最大⑤まで増やせるようにする。

**Comment by hiraokakoichi** [comment]
【メモ】
7項目 x 5件 x  2ページ = 70も変更するのであれば、テーブル定義を見直して、そもそも動的に増やせるような仕様にすることを検討すべき。

**Comment by hiraokakoichi** [comment]
支店ごとの情報を増やせるようにする。
↓以下は支店にひもづく情報
支店名,担当者所属部署,担当者名,顧客住所,電話番号,メールアドレス,FAX

**Comment by hiraokakoichi** [comment]
branchesテーブルを新たに作り支店情報を管理する

**Comment by hiraokakoichi** [comment]
csvインポート機能がある兼ね合いで、特定の項目だけ別テーブルで管理することは無理ではないが複雑な処理になるので、求人情報の請求単位②などと同じ仕組みを採用する。
