### ISSUE TITLE
平岡【高】一覧ページの見え方の変更

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#40]
一覧ページの見え方をspredsheetのようにスクロールで見れるようにする。
須貝が項目表示の追加が終わり次第の対応。
5/30の打ち合わせで話させていただいた内容になります。
@hiraokakoichi

**Comment by hiraokakoichi** [comment]
項目追加してもスクロールが必要なほど狭くはないので、表の幅を広げる対応をとる（2023/6/21）
