### ISSUE TITLE
【須貝】表示・非表示の設定

### ISSUE THREAD

**Issue by sugaigit** [sugaigit/w-crm#5]

**Comment by hiraokakoichi** [comment]
顧客一覧の削除ボタンをなくし、表示・非表示にする。

**Comment by hiraokakoichi** [comment]
## 概要
 - 削除機能はなくす
 - デフォルトで「表示」になっている顧客だけ一覧にする
 - 「すべて表示」リンクを配置
   - 非表示のみが必要か否かは須貝さんが確認予定

**Comment by sugaigit** [comment]
「表示を見る」と「非表示を見る」「全てを見る」の3項目にする　
プルダウンで選べるようにする
